server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false   # optional but recommended

  flyway:
    enabled: true         # ensure migrations run properly

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: mysupersecretkeymysupersecretkey12345
  expiration: 86400000